services:

  proxy:
    image: traefik:v2.3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./certs/selfsigned.crt:/certificates/selfsigned.crt
      - ./certs/selfsigned.key:/certificates/selfsigned.key
    ports:
      - "80:80"
      - "8090:8080"
    # Duplicate the command from docker-compose.yml to add --api.insecure=true
    command:
      # Enable Docker in Traefik, so that it reads labels from Docker services
      - --providers.docker
      # Add a constraint to only use services with the label for this stack
      - --providers.docker.constraints=Label(`traefik.constraint-label`, `traefik-public`)
      # Do not expose all Docker services, only the ones explicitly exposed
      - --providers.docker.exposedbydefault=false
      # Create an entrypoint "http" listening on port 80
      - --entrypoints.http.address=:80
      # Create an entrypoint "https" listening on port 443
      - --entrypoints.https.address=:443
      # Enable the access log, with HTTP requests
      - --accesslog
      # Enable the Traefik log, for configurations and errors
      - --log
      # Enable debug logging for local development
      - --log.level=DEBUG
      # Enable the Dashboard and API
      - --api
      # Enable the Dashboard and API in insecure mode for local development
      - --api.insecure=true
    labels:
      # Enable Traefik for this service, to make it available in the public network
      - traefik.enable=true
      - traefik.constraint-label=traefik-public
      # Dummy https-redirect middleware that doesn't really redirect, only to
      # allow running it locally
      - traefik.http.middlewares.https-redirect.contenttype.autodetect=false
      # remove the le certificate
      - traefik.http.routers.traefik-dashboard-https.tls.certresolver= 
      # Add self signed certificates
      - entrypoints.https.tls.certificates.certFile=/certificates/selfsigned.crt
      - entrypoints.https.tls.certificates.keyFile=/certificates/selfsigned.key
    networks:
      - traefik-public
      - default

  db:
    restart: "no"
    ports:
    
      - "5432:5432"

  adminer:
    restart: "no"
    ports:
      - "8080:8080"
    labels:
      # remove the default le certificate
      - traefik.http.routers.${STACK_NAME?Variable not set}-adminer-https.tls.certresolver=

  backend:
    restart: "no"
    ports:
      - "8888:8888"
    volumes:
      - ./backend/:/app #将代码挂在到容器路径
    build:
      context: ./backend
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    # command: sleep infinity  # Infinite loop to keep container alive doing nothing
    command: /start-reload.sh  #用于开发环境中的自动重载。当你修改代码时，它会自动重新启动 Uvicorn 服务器，从而应用更改。
    labels:
      # remove the defualt le certificate
      - traefik.http.routers.${STACK_NAME?Variable not set}-backend-https.tls.certresolver=

  # frontend:
  #   restart: "no"
  #   build:
  #     context: ./frontend
  #     args:
  #       - VITE_API_URL=http://${DOMAIN?Variable not set}
  #       - NODE_ENV=development

networks:
  traefik-public:
    # For local dev, don't expect an external Traefik network
    external: true