"""Add UserName Table

Revision ID: 19d7ed1f1a82
Revises: 9b787abd8523
Create Date: 2024-09-06 04:05:57.266379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '19d7ed1f1a82'
down_revision: Union[str, None] = '9b787abd8523'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usermovie',
    sa.Column('movies', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('owner_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usermovie')
    # ### end Alembic commands ###
