"""Initial migration

Revision ID: 4a5773adcafe
Revises: 
Create Date: 2024-08-31 00:10:48.505701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '4a5773adcafe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('movie',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('year', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rated', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('released', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('runtime', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('genre', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('director', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('writer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('actors', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('plot', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('awards', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('poster', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('imdb_rating', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('imdb_votes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('imdb_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metascore', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('box_office', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('production', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ratings', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
