"""add the mutable array type in user_movie table

Revision ID: a2e124a3c503
Revises: 0cf7ec9f12ad
Create Date: 2024-09-07 02:23:23.073657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'a2e124a3c503'
down_revision: Union[str, None] = '0cf7ec9f12ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
